src/REUSABLE/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

src/polls/urls.py
from . import views
from django.urls import path

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index_url"),
    path('<int:pk>/', views.DetailView.as_view(), name="detail_url"),
    path('<int:pk>/results/', views.ResultsView.as_view(), name="results_url"),
    path('<int:question_id>/vote/', views.vote, name="vote_url"),
]

src/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    """
    Database question and published data
    """
    question_text = models.CharField('Pregunta', max_length=200)
    pub_date = models.DateTimeField('Fecha de publicación')

    class Meta:
        verbose_name = "Pregunta"
        verbose_name_plural = "Preguntas"

    def was_published_recently(self):
        """
        Return a date with timezone
        """
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_filed = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = '¿Publicado hoy?'

    def __str__(self):
        """
        Return question_text as representation of an object
        """
        return self.question_text


class Choice(models.Model):
    """
    Database choice text and votes count
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField('Elección', max_length=200)
    votes = models.IntegerField('Votos', default=0)

    def __str__(self):
        """
        Return choice_text like representation of an object
        """
        return self.choice_text

src/polls/views.py
from .models import Choice, Question
from django.urls import reverse
from django.views import generic
from django.shortcuts import HttpResponseRedirect, get_object_or_404, render


class IndexView(generic.ListView):
    """
    List the latest 5 questions for publication dates
    """
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions
        """
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    """
    Detail for one question
    """
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    """
    Show result of a question
    """
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    """
    Youre vote
    """
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You did not select a choice"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results_url',
                                            args=(question_id,)))

src/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote_url' question.id %}" method="post">
{% csrf_token %}

{% for choice in question.choice_set.all %}
<input type="radio" value="{{ choice.id }}" name="choice" id="choice{{ forloop.counter }}"/>
<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
<br>
{% endfor %}
<input type="submit" value="Vote">

</form>

src/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}" type="text/css">

{% if latest_question_list %}

 <ul>
   {% for question in latest_question_list %}
   <li><a href="{% url 'polls:detail_url' question.id %}">{{ question.question_text }}</a></li>
   {% endfor %}
 </ul>

 {% else %}
   <p>No polls are available</p>

{% endif %}

src/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
  <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li> 
  {% endfor %}
</ul>

<a href="{% url 'polls:detail_url' question.id %}">Vote again?</a>